resources:
  - name:       Git
    type:       GitRepo
    configuration:
      gitProvider:  GithubDisha
      repository:   GithubDisha
      path:         dishameswania/pipeline-source
    buildOn:
      commit: true     

pipelines:
  - name: pipe1
    steps:
    - name: try1
      type: Bash
            
      execution:
          onExecute:
            - echo "hey, I am running"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong."
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job."
