resources:
  - name: build_info_nuget
    type: BuildInfo
    configuration:
      sourceArtifactory:    artdisha
      buildName:            nugetTry
      buildNumber:          1
      
  - name: dockerbuild_repo
    type: GitRepo
    configuration:
      path: dishameswania/ArtifactoryTest
      gitProvider: GithubDisha
      
  - name: docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artdisha
      buildName: docker_example
      buildNumber: 1
      
  - name: files
    type: FileSpec
    configuration:
      sourceArtifactory: artdisha
      pattern: nuget-local/*
      
  - name: docker_build_info_new
    type: BuildInfo
    configuration:
      sourceArtifactory:    artdisha
      buildName:            nugetTry
      buildNumber:          1
      
  - name:       release_bundle_new
    type:       ReleaseBundle
    configuration:
      sourceDistribution:    dist
      name:                 release5
      version:              1.0.0
      isSigned:             true
      
  - name:           Rule1
    type:           DistributionRule
    configuration:
      sourceDistribution:    dist
      serviceName:          Edge
      siteName:             IN
      cityName:             Bengaluru
      countryCodes:
        - IN

pipelines:
  - name: xrayDistribution
    steps:
      - name: build_docker
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.93.249.25:8081/docker/disha
          dockerImageTag: $pipeline_name.$run_number
          inputResources:
            - name: dockerbuild_repo
            - name: files
          integrations:
            - name: artdisha
            
      - name: push_docker_image
        type: DockerPush
        configuration:
          targetRepository: docker
          integrations:
            - name: artdisha
          inputSteps:
            - name: build_docker
            
      - name: publish_docker_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: push_docker_image
          outputResources:
            - name: docker_build_info
            
      - name: xray
        type: XrayScan
        configuration:
          inputResources:
            - name: docker_build_info
          outputResources:
            - name: docker_build_info_new 
            
        execution:
          onFailure: 
            - echo "Vulnerabilities found - please take a look at your watch violations in Xray"
          onSuccess:
            - echo "No vulnerabilities - good to proceed"
            
      - name: create_distribution
        type: CreateReleaseBundle
        configuration: 
          releaseBundleName:        release5
          releaseBundleVersion:     1.1.0
          sign: true
          inputResources: 
            - name: docker_build_info_new
          outputResources: 
            - name: release_bundle_new
            
      - name: my_distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: true
          inputResources:
            - name: release_bundle_new
              trigger: true
            - name: Rule1
              trigger: true
            
        execution:
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong."
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job."
