resources:
  - name: build_info_nuget
    type: BuildInfo
    configuration:
      sourceArtifactory:    artdisha
      buildName:            nuget_trial
      buildNumber:          1
      
  - name:       release_bundle_new
    type:       ReleaseBundle
    configuration:
      sourceDistribution:    dist
      name:                 release5
      version:              1.0.0
      isSigned:             true
      
  - name:           Rule1
    type:           DistributionRule
    configuration:
      sourceDistribution:    dist
      serviceName:          Edge
      siteName:             IN
      cityName:             Bengaluru
      countryCodes:
        - IN

pipelines:
  - name: xray and distribution
    steps:
      - name: xray
        type: XrayScan
        configuration:
          inputResources:
            - name: build_info_nuget
            
        execution:
          onFailure: 
            - echo "Vulnerabilities found - please take a look at your watch violations in Xray"
          onSuccess:
            - echo "No vulnerabilities - good to proceed"
            
      - name: create_distribution
        type: CreateReleaseBundle
        configuration: 
          releaseBundleName:        release5
          releaseBundleVersion:     1.0.0
          sign: true
          inputResources: 
            - name: build_info_nuget
          outputResources: 
            - name: release_bundle_new
            
      - name: my_distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: true
          inputResources:
            - name: release_bundle_new
              trigger: false
            - name: Rule1
              trigger: false
            
        execution:
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong."
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job."
