resources:
  - name:       release_bundle_new
    type:       ReleaseBundle
    configuration:
      sourceDistribution:    dist
      name:                 release4
      version:              1.0.0
      isSigned:             true
      
  - name:           Rule1
    type:           DistributionRule
    configuration:
      sourceDistribution:    dist
      serviceName:          Edge
      siteName:             EU
      cityName:             Moscow
      countryCodes:
        - EU

pipelines:
  - name: distribution
    steps:
      - name: my_distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: true
          inputResources:
            - name: release_bundle_new
              trigger: false
            - name: Rule1
              trigger: false
            
        execution:
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong."
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job."
